### ISSUE TITLE
jackson-parent uses different versioning than other jackson modules

### ISSUE THREAD

**Issue by seanjreilly** [FasterXML/jackson-parent#12]
Jackson parent uses the version 2.10, whereas jackson-core, jackson-annotations, jackson-databinding and so on all use version 2.10.0. This difference causes fun with things like gradle version resolution strategies.

For example, when bumping jackson versions to avoid recent CVEs, this is the difference between:

```
Closure versionStrategy = {
    eachDependency { details ->
        if (details.requested.group.startsWith("com.fasterxml.jackson")) {
                details.useVersion '2.10.0'
                details.because "spring boot 2.1.7 uses the wrong version: https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-469676"
        }
    }
}
```

which is what I would use in the perfect world, and:

```
Closure versionStrategy = {
    eachDependency { details ->
        if (details.requested.group.startsWith("com.fasterxml.jackson")) {
            if (details.requested.name == 'jackson-parent') {
                //jackson uses the version 2.10 for some things and 2.10.0 for others
                details.useVersion '2.10'
            }
            else {
                details.useVersion '2.10.0'
            }
            details.because "spring boot 2.1.7 uses the wrong version: https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-469676"
        }
    }
}
```

There was a version 2.9.0 of jackson-parent, so I'm not sure what the criteria is for any particular version number, which makes it difficult to predict ahead of time when upgrading.

**Comment by cowtowncoder** [comment]
This is by design, to reduce need to release new patch version where nothing changes. It is also not user-facing, i.e. should not be something that users should specify version for, and is pom-only dependency (no code).

So I guess I am not quite sure what the problem would actually be. But, regardless, it is versioning strategy we use, and there are no plans to change it.
As a general rule, what matters with Jackson is that minor versions match -- patch versions are nice to align, but their mis-alignment does not cause issues with compatibility as no API changes should be made (i.e. any combination of 2.10.x components should work together as a set).

I guess one other question is that of leaving out patch version -- this is because if we did use `2.10.0`, users would file issues asking about discrepancy. Leaving out patch version should indicate that patch versions are not typically released (although if one is absolutely needed, for some reason, it is still possible).

**Comment by cowtowncoder** [comment]
Oh. Forgot to address the "but there was 2.9.0 version". Yes, correct. Change has made after 2.9; patch version dropped. But before that there was no consistent set either.

So I guess what I would suggest is either not to try to force `jackson-parent` version -- it really should only be concern to "real" artifacts, which already need to specify correct version, and no user should (AFAIK) ever rely on this artifact.

**Comment by seanjreilly** [comment]
I'm not sure that I agree 100% with what you're saying about versioning, but I do I agree that users shouldn't rely on this artifact... which makes everything else moot (in fact I'm almost surprised that it's published at all, but I'm sure there's an internal reason for this).

With that in mind, I took a closer look.

I _thought_ that my project relied on it transitively somehow via another Jackson dependency, but that's actually not the case. My exact gradle error message is 

`Could not resolve all files for configuration ':detachedConfiguration3`

(detachedConfiguration3 is not the name of any configuration specified in our build files). This is weird, but it also makes me think that the spring boot plugin (I'm using spring boot) might be doing something interesting here, probably with a BOM.

I think that the best course of action is for me to open an issue with spring boot, and ask (based on your advice in this issue) why they are relying on this artifact — they might be able to remove it from a BOM.

Thanks for your help.

**Comment by cowtowncoder** [comment]
Right, it's not "user-visible". But there is no way to really hide it, either, as it must be stored and accessible via Maven Central for real components to use. Just for build purposes, but never for deployment. I mean I guess one COULD avoid release, but that would make building process for anyone else much more cumbersome as local publish would be required. And would be really nasty for CI like Travis.

Same is actually true for a few other "parent" poms for multi-artifact repos, such as "jackson-modules-base" and "jackson-dataformats-binary" -- parent pom sort of has to be used for a few reasons (to simplify release management, convenience for sharing some aspects). But then they also must be similarly published and accessible (or, someone must clone those, publish locally).

But yes, if Spring Boot is including `jackson-parent`, they should not. What can and should be used is `jackson-bom` (bill-of-materials) which defines consistent version set. It is version with full patch scheme (2.9.10, 2.10.0), and is user-facing.
