### ISSUE TITLE
Add override to downgrade `moditect-maven-plugin` from 1.2.2 to 1.1.0 to work around Eclipse issues

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-parent#15]
(for background see https://github.com/FasterXML/jackson-databind/issues/4727)

It looks like handling of zip directory entries changes in Moditect Maven plugin between 1.1 and 1.2, causing issues with Eclipse class-loading. Reported issue for plugin is:

https://github.com/moditect/moditect/issues/254

As a result, Eclipse issue now affects most Jackson 2.18.0 bundles.

So to solve the issue, let's downgrade Moditect plug-in version to `1.1.0`.
While version is defined in `oss-parent`, expectation is that there should be a newer Moditect version in future; as a result let's add temporary override in this module instead.

**Comment by Marcono1234** [comment]
@cowtowncoder, [ModiTect 1.3.0.Final](https://github.com/moditect/moditect/releases/tag/1.3.0.Final) has been released which includes a change that will likely fix this issue. At least for Gson it seems to have fixed it, see for example https://github.com/google/gson/issues/2679#issuecomment-3277437474.

Maybe would be worth giving it a try for Jackson as well.

**Comment by cowtowncoder** [comment]
@Marcono1234 Thanks! Changed things with #18 so that 2.21.x will use new Moditect plug-in version (and 3.0 for applicable cases)
