### ISSUE TITLE
Release nightly/snapshot builds of all jackson modules

### ISSUE THREAD

**Issue by Spikhalskiy** [FasterXML/jackson-parent#3]
Hi,

It's possible to find SNASHOT versions of jackson-databing in sonatype snapshot repo, but it's a but hard for some other components, even for a core.
This is how repo for databind looks like: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-databind/
And this is how repo for datatype components looks like:
https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/
So, it's empty or pretty outdates. Would be great to fix publishing of all modules.

**Comment by cowtowncoder** [comment]
I suspect this is due to travis set up from `.travis.yml`, and if so PRs would be welcome. I did not set up travis build up, but have tried to improve those over time,

**Comment by cowtowncoder** [comment]
All modules should have CI publish working, closing.
