### ISSUE TITLE
maven-enforcer-plugin overrides the managed version from oss-parent

### ISSUE THREAD

**Issue by ansell** [FasterXML/jackson-parent#5]
The maven-enforcer-plugin version in oss-parent:30 (3.0.0-M1) is compatible with Java-9, but the version is overridden here in jackson-parent to an older version.

**Comment by cowtowncoder** [comment]
Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Was fixed via this:

https://github.com/FasterXML/jackson-parent/commit/26e820473ad2e607b9b368063c653c9b90138a02

but accidentally had wrong issue id so wasn't closed.
