### ISSUE TITLE
Remove explicit scope from junit dependency declaration

### ISSUE THREAD

**Issue by jmax01** [FasterXML/jackson-parent#6]
Currently `junit` is declared with `test` scope in the `<dependencyManagement>` section.

Since`jackson-bom` is a child of `jackson-parent` users of `jackson-bom` will, without further intervention, have their `junit` dependency forced to be `test` scoped, which is not always desirable.

**Comment by cowtowncoder** [comment]
Ok. I guess that is doable, but it would seem unfortunate if this means having to add explicit scope line for every child project -- and possibly accidentally forgetting it and adding non-test dependency somewhere?

I guess I am trying to think of a better way to achieve the goal of minimizing boilerplate stuff within individual components' poms. Alternative of adding explicit test dependency in `jackson-parent` would probably be fine, assuming most people do not "extend" `jackson-bom` but import it?

**Comment by jmax01** [comment]
I am never a fan of dependencies via inheritance.

Another solution is to have an internal 3rdparty bom.
Users would not import it, but jackson projects may.
It's a good way to enforce consistency of version across modules without the issues caused by inheritance.

FYI, a quick github search of jackson poms did not reveal any junit declarations without proper test scope.

**Comment by cowtowncoder** [comment]
I think one major challenge really is that Jackson components do use `jackson-bom` via inheritance (for convenience), whereas externally it should not be used. I guess adding another layer could help; adds one more thing to release (`jackson-bom-internal`), or, maybe refactoring bom into multi-maven, 2 part thing.
